---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint tasks/*.yml
platforms:
  - name: centos7
    image: centos:7
    groups:
      - centos
  - name: ubuntu1604
    image: ubuntu:16.04
provisioner:
  name: ansible
  inventory:
    group_vars:
      centos:
        haveged_service_enable: false
scenario:
  name: default
verifier:
  name: testinfra
