---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Update APT cache
      ansible.builtin.package:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install EPEL release repo
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
        disable_gpg_check: True
      when: ansible_os_family == 'RedHat'
      become: true
