---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Update APT cache
      ansible.builtin.package:
        update_cache: yes
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: true
